### ISSUE TITLE
fetch json via fastly

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-redirect#156]
in order to use the content-proxy cache in  fastly, the redirect json should be read via fastly.

**Comment by rofe** [comment]
How/when would we purge the cache?

**Comment by tripodsan** [comment]
> How/when would we purge the cache?

via observation... ?
via sidekick (publish) ?

**Comment by rofe** [comment]
> via observation... ?

Preferrably yes, but we currently only have observation for onedrive.

> via sidekick (publish) ?

That would be an option, but currently only poissble from the "preview" (JSON) URL which is not very intuitive.
